-- MySQL Script generated by MySQL Workbench
-- Sun May 29 20:25:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema carssystem
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `carssystem` ;

-- -----------------------------------------------------
-- Schema carssystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `carssystem` DEFAULT CHARACTER SET utf8 ;
USE `carssystem` ;

-- -----------------------------------------------------
-- Table `carssystem`.`fueltypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carssystem`.`fueltypes` ;

CREATE TABLE IF NOT EXISTS `carssystem`.`fueltypes` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carssystem`.`transmissiontypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carssystem`.`transmissiontypes` ;

CREATE TABLE IF NOT EXISTS `carssystem`.`transmissiontypes` (
  `Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carssystem`.`engines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carssystem`.`engines` ;

CREATE TABLE IF NOT EXISTS `carssystem`.`engines` (
  `Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `TransmissionType` INT(10) UNSIGNED NULL DEFAULT NULL,
  `PowerCC` INT(10) UNSIGNED NULL DEFAULT NULL,
  `MaxPowerBhp` DECIMAL(10,2) UNSIGNED NULL DEFAULT NULL,
  `TorqueNm` INT(10) UNSIGNED NULL DEFAULT NULL,
  `TorqueRpmMin` INT(10) UNSIGNED NULL DEFAULT NULL,
  `TorqueRpmMax` INT(10) UNSIGNED NULL DEFAULT NULL,
  `FuelType` INT(10) UNSIGNED NULL DEFAULT NULL,
  `MileageKmpl` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `engine_fueltype_fk`
    FOREIGN KEY (`FuelType`)
    REFERENCES `carssystem`.`fueltypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `engine_trasmissiontype_fk`
    FOREIGN KEY (`TransmissionType`)
    REFERENCES `carssystem`.`transmissiontypes` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8129
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `Id_UNIQUE` ON `carssystem`.`engines` (`Id` ASC);

CREATE INDEX `engine_trasmissiontype_fk_idx` ON `carssystem`.`engines` (`TransmissionType` ASC);

CREATE INDEX `engine_fueltype_fk_idx` ON `carssystem`.`engines` (`FuelType` ASC);


-- -----------------------------------------------------
-- Table `carssystem`.`interiors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carssystem`.`interiors` ;

CREATE TABLE IF NOT EXISTS `carssystem`.`interiors` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `SeatsNumber` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8129
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carssystem`.`cars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carssystem`.`cars` ;

CREATE TABLE IF NOT EXISTS `carssystem`.`cars` (
  `Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL DEFAULT NULL,
  `Interior` INT(10) UNSIGNED NULL DEFAULT NULL,
  `Engine` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `cars_engine_fk`
    FOREIGN KEY (`Engine`)
    REFERENCES `carssystem`.`engines` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cars_interiors_fk`
    FOREIGN KEY (`Interior`)
    REFERENCES `carssystem`.`interiors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8129
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `Id_UNIQUE` ON `carssystem`.`cars` (`Id` ASC);

CREATE INDEX `cars_engine_fk__idx` ON `carssystem`.`cars` (`Engine` ASC);

CREATE INDEX `cars_interiors_fk_idx` ON `carssystem`.`cars` (`Interior` ASC);


-- -----------------------------------------------------
-- Table `carssystem`.`ownertypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carssystem`.`ownertypes` ;

CREATE TABLE IF NOT EXISTS `carssystem`.`ownertypes` (
  `Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carssystem`.`carstatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carssystem`.`carstatus` ;

CREATE TABLE IF NOT EXISTS `carssystem`.`carstatus` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `OwnerType` INT(10) UNSIGNED NULL DEFAULT NULL,
  `KmsDriven` INT(10) UNSIGNED NULL DEFAULT NULL,
  `Year` YEAR(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `carstatus_ownertype_fk`
    FOREIGN KEY (`OwnerType`)
    REFERENCES `carssystem`.`ownertypes` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8129
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `carstatus_ownertype_fk_idx` ON `carssystem`.`carstatus` (`OwnerType` ASC);


-- -----------------------------------------------------
-- Table `carssystem`.`dealers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carssystem`.`dealers` ;

CREATE TABLE IF NOT EXISTS `carssystem`.`dealers` (
  `Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Appellation` VARCHAR(5) NULL DEFAULT NULL COMMENT 'Mr./Ms./...',
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Surname` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `Id_UNIQUE` ON `carssystem`.`dealers` (`Id` ASC);


-- -----------------------------------------------------
-- Table `carssystem`.`sellertypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carssystem`.`sellertypes` ;

CREATE TABLE IF NOT EXISTS `carssystem`.`sellertypes` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `carssystem`.`deals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carssystem`.`deals` ;

CREATE TABLE IF NOT EXISTS `carssystem`.`deals` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Dealer` INT(10) UNSIGNED NULL DEFAULT NULL,
  `SellerType` INT(10) UNSIGNED NULL DEFAULT NULL,
  `Price` DECIMAL(10,2) NULL DEFAULT NULL,
  `Car` INT UNSIGNED NULL DEFAULT NULL,
  `CarStatus` INT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `deals_dealer_fk`
    FOREIGN KEY (`Dealer`)
    REFERENCES `carssystem`.`dealers` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `deals_sellertype_fk`
    FOREIGN KEY (`SellerType`)
    REFERENCES `carssystem`.`sellertypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `deals_car_fk`
    FOREIGN KEY (`Car`)
    REFERENCES `carssystem`.`cars` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `deals_carstatus_fk`
    FOREIGN KEY (`CarStatus`)
    REFERENCES `carssystem`.`carstatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8129
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `deals_dealer_fk_idx` ON `carssystem`.`deals` (`Dealer` ASC);

CREATE INDEX `deals_sellertype_fk_idx` ON `carssystem`.`deals` (`SellerType` ASC);

CREATE INDEX `deals_car_fk_idx` ON `carssystem`.`deals` (`Car` ASC);

CREATE INDEX `deals_carstatus_fk_idx` ON `carssystem`.`deals` (`CarStatus` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
